INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("ALPHA", "books", 500, "01/01/2017", "01/01/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Google", "books", 500, "01/01/2017", "01/01/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Hector", "books", 500, "01/01/2017", "01/01/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Init", "books", 500, "01/01/2017", "01/01/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Juicy", "books", 500, "01/01/2017", "01/01/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Killzone", "books", 500, "01/01/2017", "01/01/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Charlie", "books", 500, "01/01/2017", "01/01/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("DELTA", "books", 500, "01/01/2017", "01/01/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Enigma", "books", 500, "01/01/2017", "01/01/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Feast", "books", 500, "01/01/2017", "01/01/2018");
INSERT INTO users (name, age) VALUES ("Amy", 30);
INSERT INTO users (name, age) VALUES ("Jamie", 29);
INSERT INTO users (name, age) VALUES ("Cindy", 28);
INSERT INTO users (name, age) VALUES ("Mindy", 27);
INSERT INTO users (name, age) VALUES ("Carl", 27);
INSERT INTO users (name, age) VALUES ("Bob", 26);
INSERT INTO users (name, age) VALUES ("Julie", 24);
INSERT INTO users (name, age) VALUES ("Booby", 23);
INSERT INTO users (name, age) VALUES ("Welsh", 22);
INSERT INTO users (name, age) VALUES ("Grapes", 21);
INSERT INTO users (name, age) VALUES ("Sam", 20);
INSERT INTO users (name, age) VALUES ("I am", 19);
INSERT INTO users (name, age) VALUES ("LabKiller", 18);
INSERT INTO users (name, age) VALUES ("Darth", 17);
INSERT INTO users (name, age) VALUES ("Vader", 40);
INSERT INTO users (name, age) VALUES ("Seek", 39);
INSERT INTO users (name, age) VALUES ("Geek", 38);
INSERT INTO users (name, age) VALUES ("Zeek", 37);
INSERT INTO users (name, age) VALUES ("Lisa", 36);
INSERT INTO users (name, age) VALUES ("Marie", 35);

INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 5, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 7, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 8, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 9, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 10, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 11, 11);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 11, 12);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 12, 11);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 12, 12);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 13, 13);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 13, 14);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 14, 13);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 14, 14);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 15, 15);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 15, 16);
